
description : Create a new ticket for a bug.
title : ❌ Title
name : Bug Report

labels:

    -   bug

body:

    #   Pulsar Version

    -   type : textarea
        id : pulsar-version

        attributes:

            description : Version of Pulsar, check with `pulsar --version`
            label : Pulsar Version
            value : |
                Pulsar   : 1.100.0-beta
                Electron : 12.2.3
                Chrome   : 89.0.4389.128
                Node     : 14.16.0

        validations:

            required : true


    #   Package Version

    -   type : input
        id : package-version

        attributes:

            description : Version of Highlight-Line.
            placeholder : 0.12.0
            label : Package Version

        validations:

            required : true


    #   Description

    -   type : textarea
        id : description

        attributes:

            description : Please describe your problem as detailed as possible.
            label : Description
