
name: CI

#   Disabled as long as the GitHub Action
#   is not available / ppm is not properly
#   installed.
#
on:
    workflow_dispatch:

#     pull_request:

#     push:
#         branches:

#             -   main

jobs:

    Test:

        runs-on : ${{ matrix.os }}
        if : "!contains(github.event.head_commit.message,'[skip ci]')"

        strategy:
            matrix:
                channel : [ stable , beta ]
                os : [ ubuntu-latest , macos-latest , windows-latest ]

        steps:

            -   uses : actions/checkout@v3

            # -   uses : pulsar-edit/action-setup-pulsar
            #     with :
            #         channel : ${{ matrix.channel }}

            -   name : Print Pulsar's Version
                run : pulsar -v

            -   name  : Print PPM's Version
                run : ppm -v

            -   name : Install Dependencies
                run : ppm ci
                env :
                    APM_TEST_PACKAGES : minimap minimap-highlight-selected status-bar

            -   name : Run Tests
                run : npm run test


    Skip:

        runs-on : ubuntu-latest
        if : "contains(github.event.head_commit.message,'[skip ci]')"

        steps:

            -   name : Skip CI 🚫
                run : echo skip ci
