name: CI
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  Test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        channel: [stable, beta]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: UziTech/action-setup-atom@v1
        with:
          channel: ${{ matrix.channel }}
      - name: Atom version
        run: atom -v
      - name: APM version
        run: apm -v
      - name: Install dependencies
        env:
          APM_TEST_PACKAGES: 'minimap minimap-highlight-selected status-bar'
        run: apm ci
      - name: Run tests
        run: npm test
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - name: ESlint
        run: npm lint
